### ISSUE TITLE
Resizing the Annotations column doesn't work

### ISSUE THREAD

**Issue by WMAM** [Dominic-DallOsto/zotero-annotations-count#3]
I have detected a couple of bugs:

1. It is not possible to narrow this column, which is more uncomfortable when the icon is selected as the header. 
2. If you select the descending order with the “non-zero” option, the items without annotations appear first, and those with annotations last.

**Comment by helsingi** [comment]
For the first issue, restarting Zotero is needed for resizing the column.

**Comment by WMAM** [comment]
Yes, it did... Thanks!

**Comment by Dominic-DallOsto** [comment]
I moved the second issue to #4 

And yeah, the first is a known issue, same as in https://github.com/Dominic-DallOsto/zotero-reading-list/issues/27 - I'm still not sure what causes it, but it should work fine if you restart after adding this column / changing its formatting / updating the extension.

**Comment by Dominic-DallOsto** [comment]
Hi, if you're still facing this issue please let me know!
