### ISSUE TITLE
Sorting order doesn't work when hiding 0 annotation counts

### ISSUE THREAD

**Issue by Dominic-DallOsto** [Dominic-DallOsto/zotero-annotations-count#4]
> If you select the descending order with the “non-zero” option, the items without annotations appear first, and those with annotations last.

Reported by @WMAM

![image](https://github.com/user-attachments/assets/b74febd1-ce3f-4529-8e7d-9a7ff283ba08)

**Comment by Dominic-DallOsto** [comment]
See the last message [here](https://groups.google.com/g/zotero-dev/c/4jqa8QIk6DM)

> the dataProvider is also used by sorting, which uses Zotero.getLocaleCollation().compareString, which requires a string

**Comment by Dominic-DallOsto** [comment]
The solution was for the data provider to return:

```
-1 - this item can't have annotations or attachments (eg. a note)
0 - this item has not annotations
X - this item has some annotations
```

This allows proper sorting of items (which will never be -1). Then the renderer will show a blank string instead of -1, and instead of 0 if enabled in the settings.

**Comment by WMAM** [comment]
Now, the descending order works fine, but the ascending one no. But, at least for me, this is not a big problem. 

Thank you!

**Comment by Dominic-DallOsto** [comment]
For me, the ascending order first shows all the items without annotations (ie. that have 0), then shows the items with annotations in ascending order.

![image](https://github.com/user-attachments/assets/4d900c04-a784-4126-b7ef-009b0d10c792)

Do you see something different?
